### ISSUE TITLE
Image Path points to absolute directory leading to errors

### ISSUE THREAD

**Issue by msindev** [BATspock/SUAS2019#1]
The image path is hard coded and causes errors.
Replace line 7 in main.py i.e.
`image_folder_path = '/home/adityakishore/workspace/SUAS2019/IP/images/'`
with
`image_folder_path =os.path.joinos.path.dirname(os.path.abspath(__file__)),"images")`
and line 44
`cv2.imwrite('/home/adityakishore/workspace/SUAS2019/IP/croppedImages/' + str(im) +  str(j) + '.png', io[y-pad:y+h+pad, x-pad:x+w+pad])`
with
`cv2.imwrite('os.path.joinos.path.dirname(os.path.abspath(__file__)),"croppedImages")' + str(im) +  str(j) + '.png', io[y-pad:y+h+pad, x-pad:x+w+pad])`

**Comment by BATspock** [comment]
@mohitwildbeast thanks. The patch will resolve the issue
